name: Build APK from ZIP
on:
  workflow_dispatch:
  push:
    paths:
      - ziweilite_android_project.zip
      - .github/workflows/build-from-zip.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip project
        run: |
          unzip -q ziweilite_android_project.zip -d .
          shopt -s dotglob
          mv ziweilite/* .
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }
      - uses: android-actions/setup-android@v3
      - name: Install Gradle 8.7
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
      - name: Build Debug APK
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          gradle assembleDebug --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: ZiweiLite-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
